# Current Account Rules
# Rule: More tenure → Lower min balance, Higher overdraft

tenure.bucket.new=0
tenure.bucket.standard=1
tenure.bucket.premium=3

min.balance.new=25000
min.balance.standard=20000
min.balance.premium=15000

interest.rate.new=0.00
interest.rate.standard=0.00
interest.rate.premium=0.00

overdraft.limit.new=5000
overdraft.limit.standard=10000
overdraft.limit.premium=25000

feature.name.new=Regular Current
feature.name.standard=Business Current
feature.name.premium=Premium Current

daily.transfer.limit.new=100000
daily.transfer.limit.standard=500000
daily.transfer.limit.premium=1000000
daily.transfer.limit.privilege=1000000
